application:
  host: 0.0.0.0
  port: 8080

mysql:
  url: root:root@tcp(127.0.0.1:3306)/OrderManager?charset=utf8mb4&parseTime=True&loc=Locals\

redis:
  url: localhost:6379
  queues:
    orders: orders